apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.backend.name }}-service"
spec:
  selector:
    app: {{ .Values.backend.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.containerPort }}