apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.frontend.name }}-service"
spec:
  selector:
    app: {{ .Values.frontend.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.containerPort }}